version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: movie_postgres
    environment:
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: movie_password
      POSTGRES_DB: movie_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movie_user -d movie_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium_chrome
    ports:
      - "4444:4444"
    shm_size: "2g"
    restart: unless-stopped
#    environment:
#      - SE_NODE_MAX_SESSIONS=5
#      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
#      - SE_SCREEN_WIDTH=1920
#      - SE_SCREEN_HEIGHT=1080
    volumes:
      - /dev/shm:/dev/shm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: