#!/usr/bin/env python3
"""
Test script for Link Parser module
Tests that LinkParser extracts film links from URLs generated by URLGenerator
"""

import sys
import os
import logging
from typing import List

# Add project root to Python path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.parser.link_parser import create_link_parser
from src.parser.url_generator import URLGenerator


def setup_logging():
    """Setup logging for tests"""
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    # Reduce noise
    logging.getLogger('selenium').setLevel(logging.WARNING)
    logging.getLogger('urllib3').setLevel(logging.WARNING)


def test_connection_failure():
    """Test that LinkParser raises ConnectionError on site unavailability"""
    print("\n🔌 Testing site unavailability handling")

    # 1. Используем заведомо неработающий URL
    link_parser = create_link_parser()
    broken_url = "http://nonexistent-site-12345.lordfilm.invalid/"

    try:
        links = link_parser.parse_links_from_page(broken_url)
        print(f"❌ ERROR: Should raise ConnectionError but got {len(links)} links")
        return False
    except ConnectionError as e:
        print(f"✅ CORRECT: ConnectionError raised: {e}")
        return True
    except Exception as e:
        print(f"⚠️ Unexpected exception: {type(e).__name__}: {e}")
        return False
    finally:
        link_parser.close()

def test_integration():
    """
    Main test: LinkParser extracts films from URLs generated by URLGenerator
    """
    print("🧪 Testing LinkParser + URLGenerator integration")
    print("=" * 60)

    # 1. Create generators
    url_gen = URLGenerator()
    link_parser = create_link_parser()

    print(f"✅ URLGenerator base_url: {url_gen.base_url}")
    print(f"✅ LinkParser base_url: {link_parser.base_url}")

    # Check they use same base URL
    assert url_gen.base_url == link_parser.base_url, \
        "URLGenerator and LinkParser should use same base URL"

    # 2. Generate catalog pages
    catalog_pages = list(url_gen.generate_from_template(
        template_key='main_catalog',
        pages=2  # Test first 2 pages
    ))

    print(f"✅ Generated {len(catalog_pages)} catalog pages:")
    for page in catalog_pages:
        print(f"   📄 {page}")

    # 3. Parse film links from each page
    all_film_links = []

    for page_num, page_url in enumerate(catalog_pages, 1):
        print(f"\n📖 Parsing page {page_num}: {page_url}")

        try:
            film_links = link_parser.parse_links_from_page(page_url)
            print(f"   ✅ Found {len(film_links)} film links")

            # Validate links
            valid_links = 0
            for link in film_links:
                if _is_valid_film_link(link):
                    valid_links += 1
                    if valid_links <= 3:  # Show first 3
                        print(f"      🎬 {link}")
                else:
                    print(f"      ⚠️ Invalid: {link}")

            print(f"   📊 Valid film links: {valid_links}/{len(film_links)}")
            all_film_links.extend(film_links)

            # Small delay between pages
            if page_num < len(catalog_pages):
                import time
                time.sleep(1)

        except Exception as e:
            print(f"   ❌ Failed to parse page: {e}")
            continue

    # 4. Results
    print("\n" + "=" * 60)
    print("📊 FINAL RESULTS:")
    print(f"   Catalog pages parsed: {len(catalog_pages)}")
    print(f"   Total film links found: {len(all_film_links)}")

    # Remove duplicates
    unique_links = list(set(all_film_links))
    print(f"   Unique film links: {len(unique_links)}")

    if len(all_film_links) > len(unique_links):
        print(f"   ⚠️ Duplicates: {len(all_film_links) - len(unique_links)}")

    # 5. Validation
    success = True
    if len(all_film_links) == 0:
        print("❌ ERROR: No film links found")
        success = False
    else:
        # Check format of first 10 links
        valid_count = sum(1 for link in all_film_links[:10] if _is_valid_film_link(link))
        print(f"   Sample validation (first 10): {valid_count}/10 valid")

        if valid_count < 5:
            print("⚠️ WARNING: Many invalid film links")

    # 6. Cleanup
    print("\n🧹 Cleaning up...")
    link_parser.close()
    print("✅ LinkParser closed")

    return success


def _is_valid_film_link(url: str) -> bool:
    """Check if URL is a valid film link"""
    if not url:
        return False

    # Must be absolute URL
    if not url.startswith('http'):
        return False

    # Must contain /filmy/
    if '/filmy/' not in url:
        return False

    # Must be HTML page
    if not url.endswith('.html'):
        return False

    # Must not be catalog page
    if '/page/' in url:
        return False

    # Must have film ID pattern: /filmy/12345-something.html
    import re
    film_pattern = r'/filmy/\d+-[^/]+\.html$'
    return re.search(film_pattern, url) is not None


def quick_test():
    """Quick smoke test with connection check"""
    print("🚀 Quick smoke test")

    try:
        url_gen = URLGenerator()
        link_parser = create_link_parser()

        # Получаем тестовую страницу
        test_page = next(url_gen.generate_from_template(
            template_key='main_catalog',
            pages=1
        ))

        print(f"✅ Testing with: {test_page}")

        # Дополнительная проверка до парсинга
        print("🔍 Checking site accessibility...")
        try:
            # Простая проверка доступности
            import requests
            response = requests.head(test_page, timeout=10)
            print(f"   HTTP Status: {response.status_code}")
            if response.status_code != 200:
                print("⚠️ Site responded with non-200 status")
        except requests.exceptions.RequestException as e:
            print(f"⚠️ Site accessibility check failed: {e}")

        # Парсинг
        links = link_parser.parse_links_from_page(test_page)

        print(f"✅ Found {len(links)} links")

        if links:
            print("✅ LinkParser is working!")
            link_parser.close()
            return True
        else:
            print("⚠️ No links found (check selectors or site structure)")
            link_parser.close()
            return False  # Не падаем, но возвращаем False

    except ConnectionError as e:
        print(f"❌ Site unavailable (ConnectionError): {e}")
        return False
    except TimeoutError as e:
        print(f"❌ Timeout (TimeoutError): {e}")
        return False
    except Exception as e:
        print(f"❌ Quick test failed: {type(e).__name__}: {e}")
        return False


def main():
    setup_logging()
    print("🚀 Testing LinkParser")
    print("=" * 60)

    # 1. Проверка обработки недоступности сайта
    if not test_connection_failure():
        print("\n❌ Connection error handling test failed")
        return 1

    print("\n" + "=" * 60)
    print("2. Testing with real site...")

    # 2. Quick test (существующий тест)
    if not quick_test():
        print("\n❌ Quick test failed")
        return 1

    print("\n" + "=" * 60)
    print("Starting full integration test...")

    # Full integration test
    success = test_integration()

    print("\n" + "=" * 60)
    if success:
        print("🎉 LinkParser correctly extracts film links from URLGenerator pages!")
        return 0
    else:
        print("⚠️ LinkParser test completed with warnings")
        return 1


if __name__ == "__main__":
    sys.exit(main())

